ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("ProyectoWebApp.urls")),
    path('servicios/',include("servicios.urls")),
    path('blog/',include("blog.urls")),
    path('contacto/',include("contacto.urls")),
    path('tienda/',include("tienda.urls")),
    path('carro/',include("carro.urls")),
]

ProyectoWebApp/urls.py
from django.urls import path
from ProyectoWebApp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.contrib import admin
from . import views
from django.urls import path

urlpatterns = [
    path('',views.blog,name='blog',),
    path('categoria/<int:categoria_id>/',views.categoria,name='categoria',)
]

carro/urls.py
from django.urls import path
from . import views

app_name = "carro"

urlpatterns = [
    path('agregar/<int:producto_id>', views.agregar_producto, name='agregar'),
    path('eliminar/<int:producto_id>', views.eliminar_producto, name='eliminar'),
    path('restar/<int:producto_id>', views.restar_producto, name='restar'),
    path('limpiar/', views.limpiar_carro, name='limpiar'),
]

contacto/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.contacto, name='contacto'),
]

servicios/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.servicios, name='servicios'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.tienda, name='tienda'),
]

ProyectoWebApp/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Categoria(models.Model):
    categoria_id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=80,null=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'

    def __str__(self):
        return self.nombre

class Post(models.Model):
    post_id = models.AutoField(primary_key=True)
    titulo = models.CharField(max_length=80,null=False)
    contenido = models.CharField(max_length=80,null=False)
    imagen = models.ImageField(upload_to='blog',null=True,blank=True)
    autor = models.ForeignKey(User,on_delete=models.CASCADE)
    categorias = models.ManyToManyField(Categoria)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'

    def __str__(self):
        return self.titulo

carro/models.py
from django.db import models

# Create your models here.

contacto/models.py
from django.db import models

# Create your models here.

servicios/models.py
from django.db import models

# Create your models here.

class Servicio(models.Model):
    id_servicio = models.AutoField(primary_key=True)
    titulo = models.CharField(max_length=80,null=False)
    contenido = models.CharField(max_length=80,null=False)
    imagen = models.ImageField(upload_to='servicios')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'servicio'
        verbose_name_plural = 'servicios'

    def __str__(self):
        return self.titulo

tienda/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class CategoriaProd(models.Model):
    nombre = models.CharField(max_length=80)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=80)
    categorias = models.ForeignKey(CategoriaProd,on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='tienda', null=True, blank=True)
    precio = models.FloatField(null=False)
    disponibilidad = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    class Meta:
        verbose_name = 'producto'
        verbose_name_plural = 'productos'

    def __str__(self):
        return self.nombre

contacto/forms.py
from django import forms

class FormularioContacto(forms.Form):
    
    nombre = forms.CharField(label='nombre',required=True,max_length=80)
    email = forms.CharField(label='email',required=True)

    contenido = forms.CharField(label='Contenido',widget=forms.Textarea)

ProyectoWebApp/views.py
from django.shortcuts import render

# Create your views here.

def home(request):

    return render(request,"ProyectoWebApp/home.html")

blog/views.py
from django.shortcuts import render
from blog.models import Post,Categoria

# Create your views here.

def blog(request):
    
    posts = Post.objects.all()
    return render(request,"blog/blog.html",{"posts":posts})

def categoria(request,categoria_id):


    categoria = Categoria.objects.get(categoria_id=categoria_id)
    posts=Post.objects.filter(categorias=categoria)
    return render(request,"blog/categorias.html",{"categoria":categoria,"posts":posts})

carro/views.py
from django.shortcuts import render, redirect
from .carro import Carro
from tienda.models import Producto

# Create your views here.

""" VISTA AGREGAR PRODUCTO """

def agregar_producto(request, producto_id):

    carro = Carro(request) #instanciando carro

    producto = Producto.objects.get(id=producto_id) #obteniendo producto

    carro.agregar(producto) #agregando producto al carro

    return redirect("tienda")


""" VISTA ELIMINAR PRODUCTO """

def eliminar_producto(request, producto_id):
    
    carro = Carro(request) #instanciando carro

    producto = Producto.objects.get(id=producto_id) #obteniendo producto

    carro.eliminar(producto) #eliminando producto del carro

    return redirect("tienda")


""" VISTA RESTAR PRODUCTO """


def restar_producto(request, producto_id):

    carro = Carro(request)  # instanciando carro

    producto = Producto.objects.get(id=producto_id)  # obteniendo producto

    carro.restar_producto(producto)  # restando producto del carro

    return redirect("tienda")


""" LIMPIAR CARRO """

def limpiar_carro(request):
    
    carro = Carro(request)  # instanciando carro

    carro.limpiar_carro()

    return redirect("tienda")


""" def carro(request):
    
    return render(request, "carro/carro,html") """

contacto/views.py
from django.shortcuts import render, redirect
from .forms import FormularioContacto
import smtplib
from django.core.mail import EmailMessage,send_mail
from ProyectoWeb.settings import EMAIL_PORT, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD

# Create your views here.

def contacto(request):
    
    formulario = FormularioContacto()

    if request.method == 'POST':
        formulario_contacto = FormularioContacto(request.POST) #llenar info del formulario con la data del request.post

        if formulario_contacto.is_valid(): # si el formulario_contacto es valido (se ha rellenado los campos)

            formulario_contacto.cleaned_data

            nombre = request.POST.get("nombre")
            email = request.POST.get("email")
            contenido = request.POST.get("contenido")

            email = EmailMessage("Mensaje desde App django","nombre: {}\nDireccion:{}\nEmail: {}".format(nombre,email,contenido)
            ,"",['qntumforce@gmail.com'],reply_to=[email])


        try: 
            ''' send_mail('Contacto App django', 'contenido: {}'.format(
                contenido), email, ['qntumforce@gmail.com'],) '''

            email.send()

            return redirect("/contacto/?valido")

        except:
            return redirect("/contacto/?novalido")


    return render(request,"contacto/contacto.html",{'formulario':formulario})

servicios/views.py
from django.shortcuts import render
from servicios.models import Servicio

# Create your views here.
def servicios(request):
    
    servicios = Servicio.objects.all()

    return render(request, "servicios/servicios.html",{"servicios":servicios})

tienda/views.py
from django.shortcuts import render
from .models import Producto

# Create your views here.
 
def tienda(request):
    
    productos = Producto.objects.all()

    return render(request,"tienda/tienda.html",{"productos":productos})

ProyectoWebApp/templates/ProyectoWebApp/base.html
{% load static %}

<html>

<head>

    <!-- Bootstrap -->
    <link href="{% static 'ProyectoWebApp/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Fonts -->

    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">


    <!-- Styles -->
    <link href="{% static 'ProyectoWebApp/css/gestion.css' %}" rel="stylesheet">
</head>

<body>

    <h1 class="site-heading text-center text-white d-none d-lg-block">
        <span class="site-heading-lower">Gestión de Pedidos</span>
    </h1>


    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
        <div class="container">
            <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="home.html">Gestión de
                Pedidos</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav mx-auto">
                    <li class="nav-item {% if request.path == '/' %} active {% endif %} px-lg-4">
                        <a class="nav-link text-uppercase text-expanded" href="{% url 'home' %}">Inicio</a>
                    </li>
                    <li class="nav-item {% if request.path == '/servicios/' %} active {% endif %} px-lg-4">
                        <a class="nav-link text-uppercase text-expanded" href="{% url 'servicios' %}">Servicios</a>
                    </li>
                    <li class="nav-item {% if request.path == '/tienda/' %} active {% endif %} px-lg-4">
                        <a class="nav-link text-uppercase text-expanded" href="{% url 'tienda' %}">Tienda</a>
                    </li>
                    <li class="nav-item {% if request.path|slice:'10' == '/contacto/' %} active {% endif %} px-lg-4">
                        <a class="nav-link text-uppercase text-expanded" href="{% url 'contacto' %}">Contacto</a>
                    </li>
                    <li class="nav-item {% if request.path|slice:':6' == '/blog/' %} active {% endif %} px-lg-4">
                        <a class="nav-link text-uppercase text-expanded" href="{% url 'blog' %}">Blog</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>


    <!-- Heading -->
    <!-- <section class="page-section clearfix">
        <div class="container">
            <div class="intro">
                <img class="intro-img img-fluid mb-3 mb-lg-0 rounded"
                    src="{% static 'ProyectoWebApp/img/principal.jpg' %}" alt="">
                <div class="intro-text left-0 text-center bg-faded p-5 rounded">
                    <h2 class="section-heading mb-4">
                        <span class="section-heading-upper">Puntualidad</span>
                        <span class="section-heading-lower">El mejor stock</span>
                    </h2>
                    <p class="mb-3">En la puertra de tu casa en menos de 48 h con el envío normal. En menos de 24 h con
                        el envío express.
                    </p>

                </div>
            </div>
        </div>
    </section> -->


    <!-- Message -->
    <!-- <section class="page-section cta">
        <div class="container">
            <div class="row">
                <div class="col-xl-9 mx-auto">
                    <div class="cta-inner text-center rounded">
                        <h2 class="section-heading mb-4">
                            <span class="section-heading-upper">Compromiso total</span>
                            <span class="section-heading-lower">Garantizado</span>
                        </h2>
                        <p class="mb-0">Con más de 75 años de experiencia a nuestras espaldas, desde Gestión de Pedidos
                            tenemos los conocimientos y herramientas necesarios para llevar cualquier objeto a la puerta
                            de su casa con puntualidad y profesionalidad.</p>
                    </div>
                </div>
            </div>
        </div>
    </section> -->

    <!-- contenido Cambiante -->
    {% block content %}
    
    
    
    {% endblock %}


    <!-- Footer -->
    <footer class="footer text-faded text-center py-5">
        <div class="container">
            <p class="m-0">
                <a href="#" class="link">
                    <span class="fa-stack fa-lg">
                        <i class="fa fa-circle fa-stack-2x"></i>
                        <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                    </span>
                </a>
                <a href="#" class="link">
                    <span class="fa-stack fa-lg">
                        <i class="fa fa-circle fa-stack-2x"></i>
                        <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                    </span>
                </a>
                <a href="#" class="link">
                    <span class="fa-stack fa-lg">
                        <i class="fa fa-circle fa-stack-2x"></i>
                        <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
                    </span>
                </a>
            </p>
            <p class="m-0 mbt">
                <a href="sample.html" class="link">Política de privacidad</a> ·
                <a href="sample.html" class="link">Aviso legal</a> ·
                <a href="sample.html" class="link">Cookies</a>
            </p>
            <p class="m-0 mbt1">&copy; Gestión de Pedidos 2020</p>
        </div>
    </footer>

    <!-- Bootstrap -->
    <script src="{% static 'ProyectoWebApp/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'ProyectoWebApp/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>


</html>

ProyectoWebApp/templates/ProyectoWebApp/home.html
{% extends 'ProyectoWebApp/base.html' %}

{% load static %}

{% block content %}

  <!-- Heading -->
  <section class="page-section clearfix">
    <div class="container">
      <div class="intro">
        <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'ProyectoWebApp/img/principal.jpg' %}" alt="">
        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
          <h2 class="section-heading mb-4" >
            <span class="section-heading-upper">Puntualidad</span>
            <span class="section-heading-lower">El mejor stock</span>
          </h2>
          <p class="mb-3">En la puertra de tu casa en menos de 48 h con el envío normal. En menos de 24 h con el envío express.
          </p>
        
        </div>
      </div>
    </div>
  </section>


    <!-- Message -->
    <section class="page-section cta">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-inner text-center rounded">
              <h2 class="section-heading mb-4">
                <span class="section-heading-upper">Compromiso total</span>
                <span class="section-heading-lower">Garantizado</span>
              </h2>
              <p class="mb-0">Con más de 75 años de experiencia a nuestras espaldas, desde Gestión de Pedidos tenemos los conocimientos y herramientas necesarios para llevar cualquier objeto a la puerta de su casa con puntualidad y profesionalidad.</p>
            </div>
          </div>
        </div>
      </div>
    </section>
    
{% endblock %}

blog/templates/blog/blog.html
{% extends 'ProyectoWebApp/base.html' %}

{% load static %}

{% block content %}

    {% for post in posts %}
    
    
        <section class="page-section clearfix">
            <div class="container">
                <div class="intro">
                    <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{{post.imagen.url}}" alt=""
                        style="width: 50%; height:40% ">
                    <div class="intro-text left-0 text-center bg-faded p-5 rounded">
                        <h2 class="section-heading mb-4">
                            <span class="section-heading-lower">{{post.titulo}}</span>
                            <span class="section-heading-upper">{{post.contenido}}</span>
                        </h2>
                        <div style="text-align:left; font: size 0.8em;">
                            autor: {{post.autor}}
                        </div>
                    </div>
                </div>
            </div>
        </section>
    
    {% endfor %}

    <section>
        <div style="width:75%; text-align: center; margin:auto; color: white; ">

            Categorias:
            {% for post in posts %}

                {% for categoria in post.categorias.all %}

                    <a href="{% url 'categoria' categoria.categoria_id %}" class="linksCategorias"> {{categoria.nombre}} </a> &nbsp;&nbsp;&nbsp;

                {% endfor %}    
                
            {% endfor %}

        </div>
    </section>

{% endblock %}

blog/templates/blog/categorias.html
{% extends 'ProyectoWebApp/base.html' %}

{% load static %}

{% block content %}

    {% for post in posts %}
    
    
        <section class="page-section clearfix">
            <div class="container">
                <div class="intro">
                    <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{{post.imagen.url}}" alt=""
                        style="width: 50%; height:40% ">
                    <div class="intro-text left-0 text-center bg-faded p-5 rounded">
                        <h2 class="section-heading mb-4">
                            <span class="section-heading-lower">{{post.titulo}}</span>
                            <span class="section-heading-upper">{{post.contenido}}</span>
                        </h2>
                        <div style="text-align:left; font: size 0.8em;">
                            autor: {{post.autor}}
                        </div>
                    </div>
                </div>
            </div>
        </section>
    
    {% endfor %}

    <section>
        <div style="width:75%; text-align: center; margin:auto; color: white; ">

            Categorias:

            {% for post in posts %}

                {% for categoria in post.categorias.all %}

                    {{categoria.nombre}} &nbsp;&nbsp;&nbsp;

                {% endfor %}    
                
            {% endfor %}

        </div>
    </section>

{% endblock %}

carro/templates/carro/carro.html
{% extends 'ProyectoWebApp/base.html' %}

{% load static %}

{% block content %}

<!-- AQUI VA EL CONTENIDO CAMBIANTE -->

{% endblock %}

contacto/templates/contacto/contacto.html
{% extends 'ProyectoWebApp/base.html' %}

{% load static %}

{% block content %}

    <div class="contenedorFormulario">

        {% if "valido" in request.GET %}

            <p style="color:white;">Informacion enviada correctamente, gracias</p>

        {% endif %}

        <form method="POST" style="text-align: center;" >
            {% csrf_token %}

            <table style="color:white;margin: 20px auto;">{{formulario.as_table}}</table>
            <input type="submit" value="Enviar" style="width:150px">
        </form>

    </div>
{% endblock %}

servicios/templates/servicios/servicios.html
{% extends 'ProyectoWebApp/base.html' %}

{% load static %}

{% block content %}

    {% for servicio in servicios %}


        <section class="page-section clearfix">
            <div class="container">
                <div class="intro">
                    <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{{servicio.imagen.url}}"
                        alt="" style="width: 50%; height:40% ">
                    <div class="intro-text left-0 text-center bg-faded p-5 rounded">
                        <h2 class="section-heading mb-4">
                            <span class="section-heading-lower">{{servicio.titulo}}</span>
                            <span class="section-heading-upper">{{servicio.contenido}}</span>
                        </h2>

                    </div>
                </div>
            </div>
        </section>

    {% endfor %}

{% endblock %}

tienda/templates/carro/widget.html
<table class="table table-bordered" style="color:white;">

    <thead>

        <tr>

            <th colspan="3" class="text-center">

                Carro Compras

            </th>

        </tr>

        <tr>

            <th>Producto</th>
            <th>Cantidad</th>
            <th>Opciones</th>

        </tr>

    </thead>

    <tbody>
        
        {% if request.session.carro.items %} <!-- SI HAY PRODUCTOS EN EL CARRO... -->
        
            {% for key, value in request.session.carro.items %} <!-- POR CADA PRODUCTO EN EL CARRO... -->

                <tr>
                    <tr class="text-center">
                        <td>{{value.nombre}}</td>
                        <td>{{value.cantidad}}</td>
                        <td>
                            <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-am btn-success">+</a>
                            <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-am btn-success">-</a>
                            <a href="{% url 'carro:eliminar' value.producto_id %}" class="btn btn-am btn-success">del</a> <br>

                            {{value.precio}} Є
                        </td>
                    </tr>
                </tr>

            {% endfor %}

        {% else %} <!-- COMO NO HAY ELEMENTOS EN EL CARRO, ENTONCES... -->
        
            <tr>
                <td colspan="3">

                    <div class="alert alert-danger text-center">
                        Sin productos
                    </div>

                </td>
            </tr>

        {% endif %}



    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">
                Total: {{importe_total_carro}} Є
            </td>
        </tr>
    </tfoot>


</table>

tienda/templates/tienda/tienda.html
{% extends 'ProyectoWebApp/base.html' %}

{% load static %}

{% block content %}

<!-- INICIO BLOQUE CAMBIANTE -->

<div class="container">

    <div class="container">
        <div style="float:right;">
            <!-- <p style="color:white;"> Total: {{importe_total_carro}} Є</p> -->

            {% include "carro/widget.html"  %}

        </div>
    </div>

    <div class="row">
    
        {% for producto in productos %}
    
            <div class="col">
        
                <div class="card" style="width: 300px; margin: 5px 5px;">
        
                    <img src="{{producto.imagen.url}}" class="card-img-top">
        
                    <div class="cardy-body" style="text-align:center;">
        
                        <h7 class="card-tittle"> {{producto.nombre}} </h7>
                        <p class="card-text" style="color:black">{{producto.precio}}&nbsp;€</p>
        
                    </div>

                    <div class="card-footer text-center">

                        <a href="{% url 'carro:agregar' producto.id %}" class="btn btn-success">Agregar al carro</a>

                    </div>

                </div> <!-- card que se cierra -->
        
            </div>
    
    
        {% endfor %}
    
    </div>

</div>


<!-- FIN BLOQUE CAMBIANTE -->

{% endblock %}